#muduoServer makefile
Server:muduo_Server.cc
	g++ -o $@ $^  -lmuduo_net -lmuduo_base -lpthread
.PHONY:clean
clean:
	rm -f Server


# JsonTest makefile
# test:testJson.cc
# 	g++ -o $@ $^
# .PHONY:clean
# clean:
# 	rm -f test
