worker_processes 1;

events {
    worker_connections 1024;
}

stream {
    upstream chat_servers {
        server chat_server:9120;
    }

    server {
        listen 8000;
        proxy_pass chat_servers;
        proxy_connect_timeout 5s;
        proxy_timeout 1h;
    }
}
