#ifndef PUBLIC_H
#define PUBLIC_H

/*
server和client的公共文件
*/
constexpr int CHAT_PROTOCOL_VERSION = 1;

enum EnMsgType
{
    LOGIN_MSG = 1,  // 登录消息
    LOGIN_MSG_ACK,  // 登录响应消息
    LOGINOUT_MSG,   // 注销消息
    LOGINOUT_MSG_ACK, // 注销响应消息
    REG_MSG,        // 注册消息
    REG_MSG_ACK,    // 注册响应消息
    ONE_CHAT_MSG,   // 聊天消息
    ONE_CHAT_MSG_ACK, // 聊天发送响应消息
    ADD_FRIEND_MSG, // 添加好友消息
    ADD_FRIEND_MSG_ACK, // 添加好友响应消息

    CREATE_GROUP_MSG,     // 创建群组
    CREATE_GROUP_MSG_ACK, // 创建群组响应消息
    ADD_GROUP_MSG,        // 加入群组
    ADD_GROUP_MSG_ACK,    // 加入群组响应消息
    GROUP_CHAT_MSG,       // 群聊天
    GROUP_CHAT_MSG_ACK,   // 群聊天发送响应消息
    LEAVE_GROUP_MSG,      // 退群
    LEAVE_GROUP_MSG_ACK,  // 退群响应
    SET_GROUP_ROLE_MSG,   // 调整群角色
    SET_GROUP_ROLE_MSG_ACK, // 调整群角色响应
    MARK_READ_MSG,        // 已读回执
    MARK_READ_MSG_ACK,    // 已读回执响应
    RECALL_MSG,           // 撤回消息
    RECALL_MSG_ACK,       // 撤回响应
    RECALL_NOTIFY_MSG,    // 撤回通知
    QUERY_HISTORY_MSG,    // 查询历史消息
    QUERY_HISTORY_MSG_ACK,// 查询历史消息响应
    SEARCH_USER_MSG,      // 搜索用户
    SEARCH_USER_MSG_ACK,  // 搜索用户响应
    ADD_BLACKLIST_MSG,    // 加入黑名单
    ADD_BLACKLIST_MSG_ACK,// 加入黑名单响应
    REMOVE_BLACKLIST_MSG, // 移出黑名单
    REMOVE_BLACKLIST_MSG_ACK, // 移出黑名单响应
    SET_USER_STATE_MSG,   // 设置用户状态
    SET_USER_STATE_MSG_ACK, // 设置用户状态响应
    SET_NICKNAME_MSG,     // 修改昵称
    SET_NICKNAME_MSG_ACK, // 修改昵称响应

};

enum ChatErrorCode
{
    ERR_OK = 0,

    ERR_PROTOCOL_MISSING_VERSION = 4001,
    ERR_PROTOCOL_UNSUPPORTED_VERSION = 4002,
    ERR_PROTOCOL_MISSING_MSGID = 4003,
    ERR_PROTOCOL_INVALID_JSON = 4004,

    ERR_AUTH_INVALID_CREDENTIALS = 4101,
    ERR_AUTH_ALREADY_ONLINE = 4102,
    ERR_AUTH_BANNED = 4103,
    ERR_AUTH_EMPTY_CREDENTIALS = 4104,
    ERR_AUTH_HASH_FAILED = 4105,
    ERR_AUTH_REGISTER_FAILED = 4106,

    ERR_CHAT_TARGET_NOT_FOUND = 4201,
    ERR_CHAT_PERSIST_FAILED = 4202,

    ERR_FRIEND_SELF = 4301,
    ERR_FRIEND_TARGET_NOT_FOUND = 4302,
    ERR_FRIEND_ALREADY_FRIEND = 4303,
    ERR_FRIEND_BLOCKED = 4304,
    ERR_FRIEND_INSERT_FAILED = 4305,

    ERR_GROUP_USER_NOT_FOUND = 4401,
    ERR_GROUP_NAME_EMPTY = 4402,
    ERR_GROUP_CREATE_FAILED = 4403,
    ERR_GROUP_NOT_FOUND = 4404,
    ERR_GROUP_ALREADY_MEMBER = 4405,
    ERR_GROUP_JOIN_FAILED = 4406,
    ERR_GROUP_NOT_MEMBER = 4407,
    ERR_GROUP_CREATOR_CANNOT_LEAVE = 4408,
    ERR_GROUP_LEAVE_FAILED = 4409,
    ERR_GROUP_ROLE_INVALID = 4410,
    ERR_GROUP_ONLY_CREATOR_CAN_SET_ROLE = 4411,
    ERR_GROUP_TARGET_NOT_MEMBER = 4412,
    ERR_GROUP_CANNOT_CHANGE_CREATOR_ROLE = 4413,
    ERR_GROUP_SET_ROLE_FAILED = 4414,
    ERR_GROUP_CHAT_PERSIST_FAILED = 4415,
    ERR_GROUP_HISTORY_ACCESS_DENIED = 4416,
    ERR_GROUP_ROLE_PERMISSION_DENIED = 4417,
    ERR_GROUP_ADMIN_CANNOT_GRANT_ADMIN = 4418,

    ERR_MESSAGE_MARK_READ_FAILED = 4501,
    ERR_MESSAGE_RECALL_FAILED = 4502,
    ERR_MESSAGE_HISTORY_INVALID_SCOPE = 4503,

    ERR_USER_SEARCH_KEYWORD_EMPTY = 4601,
    ERR_USER_BLOCK_SELF = 4602,
    ERR_USER_BLOCK_TARGET_NOT_FOUND = 4603,
    ERR_USER_ALREADY_BLOCKED = 4604,
    ERR_USER_NOT_BLOCKED = 4605,
    ERR_USER_BLOCK_INSERT_FAILED = 4606,
    ERR_USER_UNBLOCK_FAILED = 4607,
    ERR_USER_BLOCKED_RELATION = 4608,
    ERR_USER_STATE_INVALID = 4609,
    ERR_USER_STATE_UPDATE_FAILED = 4610,
    ERR_USER_NAME_EMPTY = 4611,
    ERR_USER_NAME_UPDATE_FAILED = 4612,
};

#endif
